### PR TITLE
Unflake functional tests

### PR DESCRIPTION
**Pull request by darosior**

### CODE REVIEW

**Comment by darosior** [comment]
Ran CI 3 times and test suite locally a dozen of times with different concurrency parameters, looks legit :)

**Comment by danielabrozzoni** [comment]
CI is failing in #167 which is rebased on top of this one (https://github.com/revault/revaultd/pull/167/checks?check_run_id=2322656567), I don't think the problem is introduced in #167

**Comment by darosior** [comment]
Hmm. I'll add a commit to run with `DEBUG=1` to investigate CI failures and restart it here once again to see if it was a one time flakiness..

**Comment by darosior** [comment]
Got another timeout on CI, i can't manage to reproduce it locally and increasing the CI wait `TIMEOUT` by another minute would be insane. So we'll live with that.

**Comment by darosior** [comment]
ACK 664d416

**Comment by danielabrozzoni** [comment]
ACK `664d416c9d87b7ca159cc71bb42beeba5eb08545` - tested locally multiple times, never had failures

**Review by danielabrozzoni — APPROVED** [review]

**Pull request merged**
