### PR TITLE
Functional tests unflaking

### PR DESCRIPTION
**Pull request by darosior**

### CODE REVIEW

**Comment by darosior** [comment]
I'm at the 10th run in a row locally without failure

**Review by danielabrozzoni — APPROVED** [review]
I'm at the 5th run and it looks really good! 

ACK 85690ffc5a80df42eb25206182fedbf9e4bef33f

**Comment by darosior** [comment]
ACK 85690ff -- ran the test suite 32 times in a row without anymore reorg tests flakiness

**Comment by darosior** [comment]
Pushed a few more fixes, this is ready to go!

**Pull request merged**
