### PR TITLE
main: register a custom panic hook

### LINKED ISSUE #168: A panic in a thread should stop the main thread

### PR DESCRIPTION
**Pull request by darosior**
Fixes #168 .

I think it should help with CI, too.

### CODE REVIEW

**Comment by danielabrozzoni** [comment]
utACK bb0bbe9c2876df7b797c306016c5bd46e6d59f69

**Comment by danielabrozzoni** [comment]
I found the time for testing it :D 

ACK bb0bbe9

**Review by danielabrozzoni — APPROVED** [review]

**Comment by darosior** [comment]
And CI is still stuck. No fucking idea what's happening..

**Comment by darosior** [comment]
Great. It found a panic.

**Pull request merged**
