### PR TITLE
Small tests improvements

### PR DESCRIPTION
**Pull request by darosior**
Some stuff i noticed when testing #231

### CODE REVIEW

**Comment by danielabrozzoni** [comment]
Tests are failing on CI :(

**Comment by darosior** [comment]
Cool this uncovered another bug

**Comment by darosior** [comment]
Fixed, i think

**Review by danielabrozzoni — APPROVED** [review]
Running `test_large_spend` on this branch:
```
real    5m40.103s
user    8m44.235s
sys     0m49.403s
```

on master:
```
real    6m30.656s
user    8m43.484s
sys     0m52.359s
```
:tada:

ACK c2a2bc8238a9a0c35b3a7e3e122e955a17e0c0f5

**Pull request merged**
