### PR TITLE
Rework help command

### PR DESCRIPTION
**Pull request by danielabrozzoni**

### CODE REVIEW

**Comment by darosior** [comment]
Thanks for doing that. Needs rebase

**Comment by danielabrozzoni** [comment]
I forgot to update after #332, will do ASAP

**Comment by darosior** [comment]
(intentionally fucking with CI on this PR since you'll re-push)

**Review by darosior — COMMENTED** [review]
ACK e1f45f8559ee21d9245e727273a9f443a677fda4

Did you plan to rework this further?

**Comment by danielabrozzoni** [comment]
Rebased and added the `stop` command in `doc/API.md`; I'd say it's cool as it is for now

**Comment by darosior** [comment]
Cool, maybe add it to the `help` as well?

**Comment by danielabrozzoni** [comment]
🤦🏻‍♀️ sorry, should be ok now

**Review by darosior — COMMENTED** [review]
ACK 5f895b9ab51b74ddca1127ff25fa68ac355e9ed9

**Pull request merged**
