### PR TITLE
Bugfixes for dust deposits and `listpresignedtransactions`

### LINKED ISSUE #146: Blockheight not synced correctly
```
revault-cli getinfo
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/revault-cli --conf config.toml getinfo`
{
  "id": "revault-cli-506",
  "jsonrpc": "2.0",
  "result": {
    "blockheight": 1969353,
    "network": "testnet",
    "sync": 1,
    "vaults": 178,
    "version": "0.0.2"
  }
}
```

```
bitcoin-cli -testnet getblockchaininfo
{
  "chain": "test",
  "blocks": 1969355
...
}
```

### LINKED ISSUE #148: Crash when querying `listpresignedtransactions` with a large number of dust vaults

### PR DESCRIPTION
**Pull request by darosior**
As experienced during the demo test. Based on #152 

Fixes #148 
Fixes #146

### CODE REVIEW

**Comment by danielabrozzoni** [comment]
We'll have to find an issue for the `dust` deposits anyway, in this way you can't spend them. What if they have a lot of bitcoin fragmented in smaller outputs? What if they try with 50$ for testing?

**Comment by darosior** [comment]
Well they should not, and it will be a configuration parameter anyways

**Comment by darosior** [comment]
Bear in mind that in our case receiving small utxos may be escalated into a DOS attack against the watchtowers. I personally find the dust value to not be high enough already.

**Comment by darosior** [comment]
Rebased on master after #152 merge

**Comment by danielabrozzoni** [comment]
I didn't consider that, you're right 👌🏻 

utACK 6eebcd7048f11c20d7ddd658a63361e1a78dc250 I didn't test, but the code looks fine

**Pull request merged**
