### PR TITLE
New api method: gethistory

### PR DESCRIPTION
**Pull request by edouardparis**
`gethistory` retrieves the accounting events between two timestamps
The choice of removing the `limit` parameter in favor of a `lower_limit` timestamp is because of the need of retrieving a more large set of vaults in the sql query in order to be able to not count change and cancel outputs as deposit events

based on #280

### CODE REVIEW

**Comment by darosior** [comment]
Right we should probably contribute it upstream haha

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by edouardparis** [comment]
[WIP]
I still need to fix some previous comments and use the block timestamp

**Comment by darosior** [comment]
Check if by any chance the "received time" field in `gettransaction` is the block timestamp if the tx is confirmed

-------- Original Message --------

**Comment by edouardparis** [comment]
Deprecated in favor of #317

**Pull request closed without merging**
